services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    container_name: app
    environment:
      TZ: "Asia/Tokyo"
      PHP_XDEBUG: "On"
      PHP_XDEBUG_REMOTE_HOST: "host.docker.internal"
      PHP_IDE_CONFIG: serverName=server-xdebug
    volumes:
      - ./app:/var/www/app
#      - ./videos:/videos # videosディレクトリ配下に直接動画ファイルを配置する場合
      - ~/Movies:/videos # Moviesディレクトリ配下に配置されている動画ファイルを参照する場合
    networks:
      sample-network:

  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    container_name: node
    volumes:
      - ./app:/var/www/app
    expose:
      - "80"
    environment:
      VIRTUAL_HOST: localhost.node.sample.jp
    tty: true
    stdin_open: true
    working_dir: /var/www/app
    command:
      # build:build only(for product), docker:npm run dev on docker, bash:only start container
      docker
    networks:
      sample-network:
        aliases:
          - localhost.node.sample.jp

  nginx-app:
    image: nginx:1.28.0-alpine
    container_name: nginx-app
    expose:
      - "80"
    environment:
      VIRTUAL_HOST: localhost.app.sample.jp
    volumes:
      - ./app:/var/www/app
      - ./docker/app/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      sample-network:
        aliases:
          - localhost.app.sample.jp

  db:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    container_name: db
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/env/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      sample-network:

  nginx-proxy:
    build:
      context: ./docker/proxy
      dockerfile: Dockerfile
    container_name: nginx-proxy
    environment:
      VIRTUAL_TIMEOUT: 1800 # タイムアウト30分
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/proxy/custom.conf:/etc/nginx/conf.d/custom.conf
    networks:
      sample-network:
        aliases:
          - localhost.proxy.sample.jp

  redis:
    image: redis:5-alpine
    container_name: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./redis:/data
    networks:
      sample-network:

networks:
  sample-network:
    driver: bridge
    internal: false
    name: sample-network